library(vegan)
library(vegan3d)
###set working directory where you are storing source files and want files to be save to
setwd("/Users/agregory/Desktop/ABOR_files/viral_engraphment/test")

###load the abundance community matrix
#you want the abundance matrix formatted with columns as populations and rows as samples
ab_raw<-read.csv("transposed_all_ABOR_pop_coverage.csv", header = TRUE, row.names=1, sep = ',') 

###rarefaction - this step can take a long time
#integer_matrix <- data.matrix(ab_raw)
#interger_ab_raw<-as.integer(integer_matrix)
#source("/Users/agregory/Desktop/ABOR_files/viral_engraphment/rarefaction.txt")
#pdf("rarefaction.pdf")
#rare_ab <- rarefaction(interger_ab_raw, subsample=5, plot=TRUE, color=TRUE, error=FALSE,  legend=TRUE) #make rarefaction curves for each sample/site
#dev.off()
#write.csv(rare_ab$richness, file="data_for_all_rarefaction_curves.csv")

###richness
#richness<-specnumber(ab_raw) #calculate species richness
#richness_matrix <- data.matrix(richness)
#write.csv(richness_matrix, file="species_richness_data.csv")
#sumR <- summary(richness)
#cat("\n\n", file = "species_richness_data.csv", append = TRUE) 
#capture.output(sumR, file = "species_richness_data.csv", append = TRUE) 

###Shannon's H'
#H<- diversity(ab_raw, index = "shannon") #calculates shannon’s index
#shannon_matrix <- data.matrix(H)
#write.csv(shannon_matrix, file="shannon_diversity_data.csv")
#sumH <- summary(H) 
#cat("\n\n", file = "shannon_diversity_data.csv", append = TRUE) 
#capture.output(sumH, file = "shannon_diversity_data.csv", append = TRUE) 

###Peliou's J
#J <- H/log(specnumber(ab_raw)) #calculates peilou’s J
#peilou_matrix <- data.matrix(J)
#write.csv(peilou_matrix, file="peilou_diversity_data.csv")
#sumJ <- summary(J)
#cat("\n\n", file = "peilou_diversity_data.csv", append = TRUE) 
#capture.output(sumJ, file = "peilou_diversity_data.csv", append = TRUE) 

###calculate different dissimilarity indices coupled with permutation based analyses of variance

#load the metadata (want metadata formatted with column one filled with sample id, same as in abundance matrix, and remaining samples your metadata) 
var <- read.csv("Metadata_4_vegan.csv", header = TRUE, sep = ',')
with(var,levels(Time_Point))
#choose the hex colors for each point grouping (in order of the previous line output)
colvec <- c("#682E89", "#F191AC", "#F9C4D2", "#EB1A8E", "#08A8DD", "#278C43", "#91BE49")


#Bray-Curtis Dissimilarity (quantitative - uses abundance)
bc<-vegdist(ab_raw, method="bray", binary=FALSE) 
bc_matrix <- data.matrix(bc)  
write.csv(bc_matrix, file="bray_curtis_distances.csv")
bc.mds<-metaMDS(bc, distance = "bray", k = 2, trymax = 1000, autotransform =TRUE, noshare = 0.1, expand = TRUE, trace = 1, plot = FALSE) 
capture.output(bc.mds, file = "bray_curtis_nmds_stress_k2.txt")
pdf("bray_curtis_NDMS_k2.pdf")
plot(bc.mds, choices = c(1, 2), type="n", main = "Bray-Curtis Dissimilarities of Viral Communities (quantitative)", useDingbats=FALSE) 
with(var, points(bc.mds, display = c("sites", "species"), col = colvec[Time_Point], pch = 19, bg = colvec[Time_Point], useDingbats=FALSE))
with(var, legend("topleft", legend = levels(Time_Point), bty = "n", col = colvec, pch = 19, pt.bg = colvec, useDingbats=FALSE))
dev.off()
bc.mds3<-metaMDS(bc, distance = "bray", k = 3, trymax = 1000, autotransform =TRUE, noshare = 0.1, expand = TRUE, trace = 1, plot = FALSE) 
capture.output(bc.mds3, file = "bray_curtis_nmds_stress_k3.txt")
pdf("bray_curtis_NDMS_k3.pdf")
with(var, ordiplot3d(bc.mds3, display = c("sites", "species"), choices = 1:3, col = colvec[Time_Point], pch = 19, bg = colvec[Time_Point], ax.col = "black", arr.len = 5, grid = TRUE, box = FALSE, main = "Bray-Curtis Dissimilarities of Viral Communities (quantitative)"))
with(var, legend("topright", legend = levels(Time_Point), bty = "n", col = colvec, pch = 19, pt.bg = colvec))
dev.off()
bc_data <-read.csv("bray_curtis_distances.csv", header = TRUE, row.names=1, sep = ',')
attach(var)
#Permutation based fitting of environmental factors NMDS (nonmetric)
efbc <- envfit(bc.mds~Time_Point+Group+Rectal_Oral+High_Dose_Donor+Low_Dose_Donor, permutations=9999)
cat("Bray_Curtis_permutation_based_fitting_of_environmental_factors_NMDS", file = "bray_curtis_permutation_based_fitting_of_environmental_factors_NMDS.txt")
cat("\n\n", file = "bray_curtis_permutation_based_fitting_of_environmental_factors_NMDS.txt", append = TRUE)
capture.output(efbc, file = "bray_curtis_permutation_based_fitting_of_environmental_factors_NMDS.txt", append = TRUE)
#Permutation based fitting of environmental factors CA (metric)
CCAbc =cca(bc_data)
virusEnvFitCCAbc=envfit(CCAbc~Time_Point+Group+Rectal_Oral+High_Dose_Donor+Low_Dose_Donor, permutations=9999)
virusEnvFitCCAbc
cat("Bray_Curtis_permutation_based_fitting_of_environmental_factors_CA", file = "bray_curtis_permutation_based_fitting_of_environmental_factors_CA.txt")
cat("\n\n", file = "bray_curtis_permutation_based_fitting_of_environmental_factors_CA.txt", append = TRUE)
capture.output(virusEnvFitCCAbc, file = "bray_curtis_permutation_based_fitting_of_environmental_factors_CA.txt", append = TRUE)
detach(var)

#Jaccard Distance (qualitative - uses presence/absence) 
ji<-vegdist(ab_raw, method="jaccard", binary=TRUE) 
ji_matrix <- data.matrix(ji)
write.csv(ji_matrix, file="jaccard_distances.csv")
ji.mds<-metaMDS(ji, distance = "jaccard", k = 2, trymax = 1000, autotransform =TRUE, noshare = 0.1, expand = TRUE, trace = 1, plot = FALSE) 
capture.output(ji.mds, file = "jaccard_distance_nmds_stress_k2.txt")
pdf("jaccard_distances_NDMS_k2.pdf")
plot(ji.mds, choices = c(1, 2), type="n", main = "Jaccard Distances of Viral Communities (qualitative)", useDingbats=FALSE) 
with(var, points(ji.mds, display = c("sites", "species"), col = colvec[Time_Point], pch = 19, bg = colvec[Time_Point], useDingbats=FALSE))
with(var, legend("topleft", legend = levels(Time_Point), bty = "n", col = colvec, pch = 19, pt.bg = colvec, useDingbats=FALSE))
dev.off()
ji.mds3<-metaMDS(ji, distance = "jaccard", k = 3, trymax = 1000, autotransform =TRUE, noshare = 0.1, expand = TRUE, trace = 1, plot = FALSE) 
capture.output(ji.mds3, file = "jaccard_distance_nmds_stress_k3.txt")
pdf("jaccard_distances_NDMS_k3.pdf")
with(var, ordiplot3d(ji.mds3, display = c("sites", "species"), choices = 1:3, col = colvec[Time_Point], pch = 19, bg = colvec[Time_Point], ax.col = "black", arr.len = 5, grid = TRUE, box = FALSE, main = "Jaccard Distances of Viral Communities (qualitative)"))
with(var, legend("topright", legend = levels(Time_Point), bty = "n", col = colvec, pch = 19, pt.bg = colvec))
dev.off()
ji_data <-read.csv("jaccard_distances.csv", header = TRUE, row.names=1, sep = ',')
attach(var)
#Permutation based fitting of environmental factors NMDS (nonmetric)
efji <- envfit(ji.mds~Time_Point+Group+Rectal_Oral+High_Dose_Donor+Low_Dose_Donor, permutations=9999)
cat("Jaccard_Distance_permutation_based_fitting_of_environmental_factors_NMDS", file = "jaccard_Distance_permutation_based_fitting_of_environmental_factors_NMDS.txt")
cat("\n\n", file = "jaccard_Distance_permutation_based_fitting_of_environmental_factors_NMDS.txt", append = TRUE)
capture.output(efji, file = "jaccard_Distance_permutation_based_fitting_of_environmental_factors_NMDS.txt", append = TRUE)
#Permutation based fitting of environmental factors CA (metric)
CCAji =cca(ji_data)
virusEnvFitCCAji=envfit(CCAji~Time_Point+Group+Rectal_Oral+High_Dose_Donor+Low_Dose_Donor, permutations=9999)
virusEnvFitCCAji
cat("Jaccard_Distance_permutation_based_fitting_of_environmental_factors_CA", file = "jaccard_distance_permutation_based_fitting_of_environmental_factors_CA.txt")
cat("\n\n", file = "jaccard_distance_permutation_based_fitting_of_environmental_factors_CA.txt", append = TRUE)
capture.output(virusEnvFitCCAji, file = "jaccard_distance_permutation_based_fitting_of_environmental_factors_CA.txt", append = TRUE)
detach(var)

#Sørensen index of dissimilarity (qualitative - uses presence/absence)
ss<-vegdist(ab_raw, binary=TRUE)  
ss_matrix <- data.matrix(ss)
write.csv(ss_matrix, file="sorensen_distances.csv")
ss.mds<-metaMDS(ss, k = 2, trymax = 1000, autotransform =TRUE, noshare = 0.1, expand = TRUE, trace = 1, plot = FALSE) 
capture.output(ss.mds, file = "sorensen_distance_nmds_stress_k2.txt")
pdf("sorensen_distances_NDMS_k2.pdf")
plot(ss.mds, choices = c(1, 2), type="n", main = "Sorensen Distances of Viral Communities (qualitative)") 
with(var, points(ss.mds, display = c("sites", "species"), col = colvec[Time_Point], pch = 19, bg = colvec[Time_Point]))
with(var, legend("topleft", legend = levels(Time_Point), bty = "n", col = colvec, pch = 19, pt.bg = colvec))
dev.off()
ss.mds3<-metaMDS(ss, k = 3, trymax = 1000, autotransform =TRUE, noshare = 0.1, expand = TRUE, trace = 1, plot = FALSE) 
capture.output(ss.mds3, file = "sorensen_distance_nmds_stress_k3.txt")
pdf("sorensen_distances_NDMS_k3.pdf")
with(var, ordiplot3d(ss.mds3, display = c("sites", "species"), choices = 1:3, col = colvec[Time_Point], pch = 19, bg = colvec[Time_Point], ax.col = "black", arr.len = 5, grid = TRUE, box = FALSE, main = "Sorensen Distances of Viral Communities (qualitative)"))
with(var, legend("topright", legend = levels(Time_Point), bty = "n", col = colvec, pch = 19, pt.bg = colvec))
dev.off()
ss_data <-read.csv("sorensen_distances.csv", header = TRUE, row.names=1, sep = ',')
attach(var)
#Permutation based fitting of environmental factors NMDS (nonmetric)
efss <- envfit(ji.mds~Time_Point+Group+Rectal_Oral+High_Dose_Donor+Low_Dose_Donor, permutations=9999)
cat("Sorensen_permutation_based_fitting_of_environmental_factors_NMDS", file = "sorensen_permutation_based_fitting_of_environmental_factors_NMDS.txt")
cat("\n\n", file = "sorensen_permutation_based_fitting_of_environmental_factors_NMDS.txt", append = TRUE)
capture.output(efss, file = "sorensen_permutation_based_fitting_of_environmental_factors_NMDS.txt", append = TRUE)
#Permutation based fitting of environmental factors CA (metric)
CCAss =cca(ss_data)
virusEnvFitCCAss=envfit(CCAss~Time_Point+Group+Rectal_Oral+High_Dose_Donor+Low_Dose_Donor, permutations=9999)
virusEnvFitCCAss
cat("Sorensen_permutation_based_fitting_of_environmental_factors_CA", file = "sorensen_permutation_based_fitting_of_environmental_factors_CA.txt")
cat("\n\n", file = "sorensen_permutation_based_fitting_of_environmental_factors_CA.txt", append = TRUE)
capture.output(virusEnvFitCCAss, file = "sorensen_permutation_based_fitting_of_environmental_factors_CA.txt", append = TRUE)
detach(var)

